### ISSUE TITLE
Build on OS X 10.12.2

### ISSUE THREAD

**Issue by supermensa** [akrennmair/newsbeuter#489]
When running ```make``` on OS X:

```
Makefile:30: config.mk: No such file or directory
Checking for package sqlite3... found
Checking for package libcurl... found
Checking for package libxml-2.0... found
Checking for package stfl... found
Checking for package json... not found
Checking for package json-c... found
Checking for package ncurses5.4 using ncurses5.4-config... found
c++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"77bfb\" -I/usr/include/libxml2 -I/usr/local/Cellar/libstfl/0.24_1/include -I/usr/local/Cellar/json-c/0.12/include/json-c -I/usr/include/ncurses -o src/configcontainer.o -c src/configcontainer.cpp
In file included from src/configcontainer.cpp:1:
./config.h:20:10: fatal error: 'libintl.h' file not found
#include <libintl.h>
```

I've also tried with the 'c++11' branch with no luck. Could you provide instructions as how to get libintl installed (if possible on os x).

**Comment by Minoru** [comment]
I think you need to install `gettext`, [like we do on Travis CI](https://github.com/akrennmair/newsbeuter/blob/master/travis-get-deps.sh#L15):

```console
$ brew install "gettext" && brew link --force "gettext"
```

**Comment by supermensa** [comment]
Still libintl.h:

```c++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"77bfb\" -I/usr/include/libxml2 -I/usr/local/Cellar/libstfl/0.24_1/include -I/usr/local/Cellar/json-c/0.12/include/json-c -I/usr/include/ncurses -o src/configcontainer.o -c src/configcontainer.cpp
In file included from src/configcontainer.cpp:1:
./config.h:20:10: fatal error: 'libintl.h' file not found
#include <libintl.h>
         ^
1 error generated.
make: *** [src/configcontainer.o] Error 1```

**Comment by Minoru** [comment]
Just to make sure: you did run the "link" step, did you? Some links on the Internet mention that it was the thing that fixed the issue.

Google results seem to be inconclusive as to where the header should come from on OS X—some say it's gettext, others say it's shipped with the system.

What does `locate libintl.h` say? Some results reported that the header isn't linked from `/usr/include` (the standard location for header files). Maybe that's what's happening in your case, too.

**Comment by supermensa** [comment]
Yes, did the "link" step as well.

Location of `libintl.h` ("locate" doesn't exist on os x, using "mdfind"):
`/usr/local/Cellar/gettext/0.19.8.1/include/libintl.h`

**Comment by Minoru** [comment]
Then you should be able to build Newsbeuter like this:
```console
$ CXXFLAGS=-I/usr/local/cellar/gettext/0.19.8.1/include/ make
```

**Comment by supermensa** [comment]
Hmm, got me this far:

`
c++ -I/usr/local/cellar/gettext/0.19.8.1/include/ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"77bfb\" -I/usr/include/libxml2 -I/usr/local/Cellar/libstfl/0.24_1/include -I/usr/local/Cellar/json-c/0.12/include/json-c -I/usr/include/ncurses -o src/configcontainer.o -c src/configcontainer.cpp
In file included from src/configcontainer.cpp:9:
include/utils.h:12:10: fatal error: 'libxml/parser.h' file not found
#include <libxml/parser.h>
         ^
1 error generated.
make: *** [src/configcontainer.o] Error 1
`

---

Am I the only one having trouble compiling on OS X? I should have all the dependencies listed in the "travis-get-deps.sh" file

**Comment by Minoru** [comment]
What does `ls /usr/include/libxml2` say? Should list `libxml` directory (and `ls /usr/include/libxml2/libxml/` should mention `parser.h`.)

I don't recall such issues being discussed here, on the mailing list or on IRC. Apparently you're the first one =\ I gave a shout out on IRC, maybe some other OS X user will have something to say about all this.

**Comment by supermensa** [comment]
I hadn't opened Xcode, in a couple of weeks, which handles a lot of the developer parts on os x.
A simple ```xcode-select --install``` fixed the problem and made me able to build.
