### ISSUE TITLE
Huge pile of compilation errors from the latest version on git

### ISSUE THREAD

**Issue by kozross** [akrennmair/newsbeuter#533]
I get a giant pile of errors when trying to build from source from the latest git. I get the following:

```
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"f8db\" -I/usr/include/libxml2 -I/usr/include/json-c -D_GNU_SOURCE -D_DEFAULT_SOURCE -DHAVE_OPENSSL=1 -o filter/Scanner.o -c filter/Scanner.cpp
filter/Scanner.cpp: In member function ‘Token* Scanner::NextToken()’:
filter/Scanner.cpp:587:12: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
         ~~~^~~~~~~
filter/Scanner.cpp:587:26: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
                       ~~~^~~~~~~
filter/Scanner.cpp:587:42: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
                                       ~~~^~~~~~~
filter/Scanner.cpp:587:56: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
                                                     ~~~^~~~~~~
filter/Scanner.cpp:587:86: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
                                                                                   ~~~^~~~~~~
filter/Scanner.cpp:587:100: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
                                                                                                 ~~~^~~~~~~
filter/Scanner.cpp:591:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if (ch <= L'!' || (ch >= L'#' && ch <= 65535)) {AddCh(); goto case_4;}
        ~~~^~~~~~~
filter/Scanner.cpp:591:26: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if (ch <= L'!' || (ch >= L'#' && ch <= 65535)) {AddCh(); goto case_4;}
                       ~~~^~~~~~~
filter/Scanner.cpp:600:12: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'0' && ch <= L'9')) {AddCh(); goto case_6;}
         ~~~^~~~~~~
filter/Scanner.cpp:600:26: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'0' && ch <= L'9')) {AddCh(); goto case_6;}
                       ~~~^~~~~~~
filter/Scanner.cpp:604:12: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'0' && ch <= L'9')) {AddCh(); goto case_8;}
         ~~~^~~~~~~
filter/Scanner.cpp:604:26: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'0' && ch <= L'9')) {AddCh(); goto case_8;}
                       ~~~^~~~~~~
filter/Scanner.cpp:609:12: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'0' && ch <= L'9')) {AddCh(); goto case_8;}
         ~~~^~~~~~~
filter/Scanner.cpp:609:26: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'0' && ch <= L'9')) {AddCh(); goto case_8;}
                       ~~~^~~~~~~
filter/Scanner.cpp:614:12: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'0' && ch <= L'9')) {AddCh(); goto case_9;}
         ~~~^~~~~~~
filter/Scanner.cpp:614:26: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'0' && ch <= L'9')) {AddCh(); goto case_9;}
                       ~~~^~~~~~~
filter/Scanner.cpp:619:12: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
         ~~~^~~~~~~
filter/Scanner.cpp:619:26: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
                       ~~~^~~~~~~
filter/Scanner.cpp:619:42: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
                                       ~~~^~~~~~~
filter/Scanner.cpp:619:56: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
                                                     ~~~^~~~~~~
filter/Scanner.cpp:619:86: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
                                                                                   ~~~^~~~~~~
filter/Scanner.cpp:619:100: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
                                                                                                 ~~~^~~~~~~
filter/Scanner.cpp:620:17: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    else if ((ch >= L'0' && ch <= L'9')) {AddCh(); goto case_6;}
              ~~~^~~~~~~
filter/Scanner.cpp:620:31: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    else if ((ch >= L'0' && ch <= L'9')) {AddCh(); goto case_6;}
                            ~~~^~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:112: filter/Scanner.o] Error 1
```

Steps to reproduce the issue:

1. Clone the latest from git
2. Run ``make``.
3. Observe the errors.

I have g++ 6.3.1 20170306 (according to ``g++ --version``).

**Comment by Minoru** [comment]
Wonder why [Travis didn't catch this](https://travis-ci.org/akrennmair/newsbeuter/jobs/220344381)—does 6.2.0 20160901 that's [used there](https://travis-ci.org/akrennmair/newsbeuter/jobs/220344381#L283) differ *that* much from 6.3.1?

You can try doing `export CXXFLAGS=-Wno-sign-compare` before compiling, but that probably won't help because it'll be overridden by `-Wall`.

I don't really want to modify this `Scanner` stuff because it's autogenerated, so this will probably be fixed only as part of #299.

**Comment by x4121** [comment]
Strange, did a 'clean' build on a Ubuntu 17.04 docker container with only build dependencies (debhelper, devscripts, build-essential + whats in the "control" file) and it worked fine as well :/

That used g++ 6.3.0 20170406

**Comment by Minoru** [comment]
Compiler versions don't seem right. g++ 6.3.1 has date 20170306 but 6.3.0 has 20170406?

**Comment by x4121** [comment]
`g++ (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406`

Ubuntu/Debian manages their system packages separate (mostly to provide security patches to older versions)

**Comment by Minoru** [comment]
I thought "6.3.0 20170406" is upstream version and Debian/Ubuntu only change package version ("6.3.0-12ubuntu2" in your case). If it's so, then the date on 6.3.0 should be earlier than the date on 6.3.1. Or is it a build date?

**Comment by x4121** [comment]
I guess it's the build date. '6.3.0' should be the upstream version. But yes.. it's confusing :confused:
